version: 2
updates:
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/package/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "t-tsuji"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for pip (backend)
  - package-ecosystem: "pip"
    directory: "/package/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "t-tsuji"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for pip (infrastructure)
  - package-ecosystem: "pip"
    directory: "/package/infra"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "t-tsuji"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "t-tsuji"
    commit-message:
      prefix: "chore"
      include: "scope"
