version: "3"

env:
  AWS_PROFILE: "default"

tasks:
  install-deps:
    desc: "Install Lambda layer dependencies from backend"
    dir: infrastructure
    cmds:
      - mkdir -p .layers/python
      - cd ../backend && uv export --no-hashes --no-dev | grep -v "^-e" > ../infrastructure/.layers/requirements.txt
      - uv pip install -r .layers/requirements.txt --target .layers/python --no-cache-dir --python-version 3.13

  clean:
    desc: "Clean build artifacts"
    dir: infrastructure
    cmds:
      - rm -rf .layers
      - rm -rf cdk.out

  diff:
    desc: "Show CDK diff"
    deps: [install-deps]
    dir: infrastructure
    cmds:
      - uv run cdk diff --all

  synth:
    desc: "Synthesize CDK templates"
    deps: [install-deps]
    dir: infrastructure
    cmds:
      - uv run cdk synth --all

  deploy:
    desc: "Deploy all stacks"
    deps: [install-deps]
    dir: infrastructure
    cmds:
      - uv run cdk deploy --all --require-approval never

  deploy-waf:
    desc: "Deploy WAF stack only"
    deps: [install-deps]
    dir: infrastructure
    cmds:
      - uv run cdk deploy ShirayukiTomoFansiteDevWafStack --require-approval never

  deploy-main:
    desc: "Deploy main stack only"
    deps: [install-deps]
    dir: infrastructure
    cmds:
      - uv run cdk deploy ShirayukiTomoFansiteDevStack --require-approval never

  bootstrap:
    desc: "Bootstrap CDK environments"
    dir: infrastructure
    cmds:
      - uv run cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/us-east-1
      - uv run cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/ap-northeast-1

  check-ssm:
    desc: "Check SSM parameter for WebACL ARN"
    cmds:
      - aws ssm get-parameter --name /shirayuki-tomo-fansite/dev/waf/webacl-arn --region ap-northeast-1

  destroy:
    desc: "Destroy all stacks"
    dir: infrastructure
    cmds:
      - uv run cdk destroy --all --force

  lint:
    desc: "Run linting and type checking"
    dir: infrastructure
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .
      - uv run mypy stacks/

  test:
    desc: "Run tests"
    dir: infrastructure
    cmds:
      - uv run pytest tests/

  # Backend tasks
  backend:lint:
    desc: "Run backend linting and type checking"
    dir: backend
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .
      - uv run mypy app/

  backend:test:
    desc: "Run backend tests"
    dir: backend
    cmds:
      - uv run pytest tests/

  backend:dev:
    desc: "Run backend development server"
    dir: backend
    cmds:
      - uv run python main.py